### ISSUE TITLE
setGlobalData is not a function

### ISSUE THREAD

**Issue by joshtemple** [rohit-gohri/redocusaurus#15]
Hi Rohit,

I'm getting this error when building my project after following the install instructions.

I'm on version 0.3.2 of redocusaurus.

```
TypeError: setGlobalData is not a function
    at Object.contentLoaded (/Users/joshtemple/repos/spectacles-docs/node_modules/docusaurus-theme-redoc/dist/index.js:27:13)
    at Promise.all.plugins.map (/Users/joshtemple/repos/spectacles-docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:74:22)
    at Array.map (<anonymous>)
    at Object.loadPlugins (/Users/joshtemple/repos/spectacles-docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:60:31)
error Command failed with exit code 1.
```

**Comment by joshtemple** [comment]
Solved by updating my Node and Docusaurus versions to the latest.
