### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by AlexisTonneau** [rohit-gohri/redocusaurus#183]
Is anyone experiencing this error? I cannot perform a build anymore. I tried with different schema types and different versions but it didn't succeed

```
[ERROR] Docusaurus server-side rendering could not render static page with path "/api/".

TypeError: Cannot set properties of undefined (setting 'triple-quoted-string')
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
````

**Comment by rohit-gohri** [comment]
Can you tell which version of docusaurus and redocusaurus are you using?

**Comment by rohit-gohri** [comment]
Can you add the error and stacktrace from the browser? Also your problem might be fixed by this comment: https://github.com/rohit-gohri/redocusaurus/issues/68#issuecomment-877902022 

Maybe we should merge language settings and always add scala

**Comment by rohit-gohri** [comment]
@AlexisTonneau Are you also using `additionalLanguages` ?

**Comment by rohit-gohri** [comment]
Can you remove the `scala` language and try version v1.1.1? It should automatically add `scala` lang

**Comment by rohit-gohri** [comment]
@AlexisTonneau Does 1.1.1 fix your issue?

**Comment by rohit-gohri** [comment]
That is same as https://github.com/rohit-gohri/redocusaurus/issues/174. Will see

**Comment by rohit-gohri** [comment]
Additional languages fixed in #187 and #174 fixed in  #206

**Comment by saul-data** [comment]
I had the same issue with version 2.0.2

I added in java as an additional language. The fix was to add scala too.
```
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ["bash", "csharp", "java", "php", "ruby", "scala"],
      },
```

Error:
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'triple-quoted-string')
    at Object.extend (prism.js:345:16)
    at eval (prism-scala.js:1:41)
    at ./node_modules/prismjs/components/prism-scala.js (vendors-node_modules_docusaurus-theme-redoc_dist-jsx_theme_ApiDoc_index_js.js:2105:1)
    at __webpack_require__ (runtime~main.js:34:32)
    at fn (runtime~main.js:334:21)
    at eval (redoc.browser.lib.js:41:12173)
    at eval (redoc.browser.lib.js:1819:3806)
    at eval (redoc.browser.lib.js:1819:3811)
    at eval (redoc.browser.lib.js:2:37)
    at eval (redoc.browser.lib.js:2:43)
```
