### ISSUE TITLE
Unable to build due to "Module not found: Can't resolve 'core-js/es/promise'"

### ISSUE THREAD

**Issue by tombusby** [rohit-gohri/redocusaurus#22]
I followed the instructions at https://www.npmjs.com/package/redocusaurus and I'm faced with the following build error:

```
tom@marvin ~/.../flow/docs/docusaurus % npm run build                  13:52:55

> flow-doc@0.0.0 build /home/tom/Documents/scrive/kontrakcja/backend/flow/docs/docusaurus
> docusaurus build

[en] Creating an optimized production build...

✖ Client
  Compiled with some errors in 32.66s

● Server █████████████████████████ building (70%) 831/831 modules 0 active
 



./node_modules/redoc/bundles/redoc.lib.js
Module not found: Can't resolve 'core-js/es/promise' in '/home/tom/Documents/scrive/kontrakcja/backend/flow/docs/docusaurus/node_modules/redoc/bundles'
Client bundle compiled with errors therefore further build is impossible.
./node_modules/redoc/bundles/redoc.lib.js
Module not found: Error: Can't resolve 'core-js/es/promise' in '/home/tom/Documents/scrive/kontrakcja/backend/flow/docs/docusaurus/node_modules/redoc/bundles'
 @ ./node_modules/redoc/bundles/redoc.lib.js 6760:17-46
 @ ./node_modules/docusaurus-theme-redoc/dist-jsx/theme/Redoc/Redoc.jsx
 @ ./node_modules/docusaurus-theme-redoc/dist-jsx/theme/Redoc/index.js
 @ ./node_modules/docusaurus-theme-redoc/dist-jsx/theme/ApiDoc/ApiDoc.jsx
 @ ./node_modules/docusaurus-theme-redoc/dist-jsx/theme/ApiDoc/index.js
 @ ./.docusaurus/registry.js
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/@docusaurus/core/lib/client/clientEntry.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-doc@0.0.0 build: `docusaurus build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flow-doc@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2021-04-27T11_54_02_152Z-debug.log
```

error log listed at the bottom:

```
% cat /home/tom/.npm/_logs/2021-04-27T11_54_02_152Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.10
3 info using node@v10.24.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle flow-doc@0.0.0~prebuild: flow-doc@0.0.0
6 info lifecycle flow-doc@0.0.0~build: flow-doc@0.0.0
7 verbose lifecycle flow-doc@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle flow-doc@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tom/Documents/scrive/kontrakcja/backend/flow/docs/docusaurus/node_modules/.bin:/home/tom/.cabal/bin:/home/tom/.ghcup/bin:/home/tom/.nix-profile/bin:/home/tom/.npm-global/lib/node_modules/bin/:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/:/home/tom/.cabal/bin:/home/tom/.ghcup/bin:/home/tom/.cabal/bin:/home/tom/.ghcup/bin:/home/tom/.nix-profile/bin:/home/tom/.npm-global/lib/node_modules/bin/:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/:/home/tom/.cabal/bin:/home/tom/.ghcup/bin:/home/tom/.cargo/bin:/home/tom/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin
9 verbose lifecycle flow-doc@0.0.0~build: CWD: /home/tom/Documents/scrive/kontrakcja/backend/flow/docs/docusaurus
10 silly lifecycle flow-doc@0.0.0~build: Args: [ '-c', 'docusaurus build' ]
11 silly lifecycle flow-doc@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle flow-doc@0.0.0~build: Failed to exec build script
13 verbose stack Error: flow-doc@0.0.0 build: `docusaurus build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid flow-doc@0.0.0
15 verbose cwd /home/tom/Documents/scrive/kontrakcja/backend/flow/docs/docusaurus
16 verbose Linux 4.19.0-16-amd64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.24.0
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error flow-doc@0.0.0 build: `docusaurus build`
22 error Exit status 1
23 error Failed at the flow-doc@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I've done some reading on various similar issues, but it doesn't look like I can fix this without trying to fix the deps that your package itself specifies.

**Comment by rohit-gohri** [comment]
Could you share your `package.json` and `package-lock.json`/`yarn.lock` if possible?

**Comment by tombusby** [comment]
Sure, FYI it's only at the point where I add this where things start to go wrong:

```
    [
      'redocusaurus',
      {
        specs: [{
          specUrl: 'https://redocly.github.io/redoc/openapi.yaml',
        }],
      }
    ],
```

package.json:

```{
  "name": "flow-doc",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "serve": "docusaurus serve",
    "clear": "docusaurus clear"
  },
  "dependencies": {
    "@docusaurus/core": "2.0.0-alpha.70",
    "@docusaurus/preset-classic": "2.0.0-alpha.70",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "redoc": "^2.0.0-rc.45",
    "redocusaurus": "^0.3.4"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

(the `"redoc": "^2.0.0-rc.45",` was added in an attempt to try to fix it. it fails without this too)

lock file is attached (would only let me attach it as a zip_.

[package-lock.zip](https://github.com/rohit-gohri/redocusaurus/files/6384421/package-lock.zip)

**Comment by rohit-gohri** [comment]
This is definitely an issue with dependency resolution. `@docusaurus/core` uses `core-js@2.x` while `redoc` uses `core-js@3.x`. Could you try removing `node_modules` and `package-lock.json` and try building with fresh node modules?

**Comment by rohit-gohri** [comment]
Or adding `core-js@3.x` as a dependency?

**Comment by Christopher-Hsieh** [comment]
> Or adding `core-js@3.x` as a dependency?

I have not tried this yet.

But i did do a clean install on the [example project](https://github.com/rohit-gohri/redocusaurus/tree/main/example)
With the docusaurus deps upgraded, e.g.
```
  "dependencies": {
    "@docusaurus/core": "^2.0.0-alpha.73",
    "@docusaurus/preset-classic": "^2.0.0-alpha.73",
    "redocusaurus": "^0.3.4"
  },

```
and received a similar error.

**Comment by rohit-gohri** [comment]
Thanks for trying that out. Will check with updated dependencies.

**Comment by rohit-gohri** [comment]
This should no longer be a problem in v0.4.0 (to be used with `docusaurus@2.0.0-beta.0`. Since now it also uses core-js@3.x

**Comment by Christopher-Hsieh** [comment]
This update works great! I love the new examples you've added as well. I'm really pleased, thanks for your work!
