### ISSUE TITLE
Build fails when config includes redocusaurus and docusaurus-theme-search-typesense

### ISSUE THREAD

**Issue by GalexyN** [rohit-gohri/redocusaurus#236]
Hi

I'm getting a build error when I compile with 2 plugins in the same config
- redocusaurus 1.3.0
- docusaurus-theme-search-typesense 0.7-0.0

I've noticed that if I were to comment out the redocusaurus config in presets of `docusaurus.config.js` OR `themes:['docusaurus-theme-search-typesense']` the build happens smoothly

_docusaurus.config.js_

```
  presets: [
    [
      '@docusaurus/preset-classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
    [
      'redocusaurus',
      {
        specs: [
          {
            spec: './static/api_spec/open-api-spec.yml',
            route: '/api',
          },
        ],
        theme: {
          primaryColor: '#2e8555',
          primaryColorDark: '#25c2a0'
        },
      },
    ],
  ],
  themes: ['docusaurus-theme-search-typesense'],

```

_package.json_

```
{
  "name": "json-api-docs",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@docusaurus/core": "^2.1.0",
    "@docusaurus/preset-classic": "^2.1.0",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.2.1",
    "docusaurus-theme-search-typesense": "^0.7.0-0",
    "prism-react-renderer": "^1.3.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "redocusaurus": "^1.3.0"
  },
  "devDependencies": {
    "@docusaurus/module-type-aliases": "^2.1.0",
    "@tsconfig/docusaurus": "^1.0.5",
    "typescript": "^4.7.4"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "engines": {
    "node": ">=16.14"
  }
}
```

_error message_
```
[INFO] [en] Creating an optimized production build...
✔ Client
✖ Server
  Compiled with some errors in 15.89s

main:55529
                {}.DEBUG = namespaces;
                  ^

SyntaxError: Unexpected token '.'
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at .../json-api-docs/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at .../json-api-docs/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (.../json-api-docs/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] Docusaurus version: 2.1.0
Node version: v16.14.2

```

**Comment by balazsbotond** [comment]
I have the exact same issue. It would be great to be able to use both search and redocusaurus at the same time, but honestly I have no idea where to even start debugging it.

**Comment by balazsbotond** [comment]
I made a minimal example to reproduce the bug, I hope it will help whoever can debug this:

https://github.com/balazsbotond/redocusaurus-typesense-bug-repro

**Comment by balazsbotond** [comment]
Please note that @GalexyN also reported the same issue here: https://github.com/typesense/docusaurus-theme-search-typesense/issues/23

I've found a [closed issue about the same problem](https://github.com/debug-js/debug/issues/467) in the [debug.js](https://github.com/debug-js/debug) project.

A [PR which fixed this issue with minimal changes](https://github.com/debug-js/debug/pull/590) was rejected with the justification that "it wasn't the maintainers' job to fix other people's messes". [Another PR](https://github.com/debug-js/debug/pull/560) which may fix this issue has been open for more than four years.

The [original issue](https://github.com/debug-js/debug/issues/467) offers several possible workarounds by defining webpack plugins but I'm not sure these can be added to a Docusaurus project.

One of my coworkers suggested simply commenting out the offending line in the `node_modules` folder (`node_modules/debug/src/node.js`):

```js
function save(namespaces) {
	const env = process.env;
	if (namespaces) {
		// env.DEBUG = namespaces;
	} else {
		// If you set a process.env field to null or undefined, it gets cast to the
		// string 'null' or 'undefined'. Just delete instead.
		delete env.DEBUG;
	}
}
```

Which, while being an incredibly hacky solution, is the one we currently use as part of our CI pipeline by running the following sed command after installing npm packages:

```
sed -i '/process.env.DEBUG = namespaces;/c\// process.env.DEBUG = namespaces;' ./node_modules/debug/src/node.js
```

Far from ideal, I know, but I hope it helps someone until the root cause is fixed.

**Comment by rohit-gohri** [comment]
> defining webpack plugins but I'm not sure these can be added to a Docusaurus project.

This is very easy to do. We already do it here - https://github.com/rohit-gohri/redocusaurus/blob/main/packages/docusaurus-theme-redoc/src/index.ts#L20-L23 


If some one can open a PR, I'll be happy to review and release it. Thanks @balazsbotond for the research on the issue!

**Comment by rohit-gohri** [comment]
Probably this is the culprit - https://github.com/rohit-gohri/redocusaurus/blob/45a314be01a4db4d8196be519d52ab61cf15b26f/packages/docusaurus-theme-redoc/src/index.ts#L29

**Comment by Sakura-pgh** [comment]
I solved the problem by changing this in `docusaurus.config.js`

```js
plugins: [
    ...
    async function customPlugin(context, opts) {
      return {
        name: 'custom-plugin',
        configureWebpack(config, isServer, utils, content) {
          // Modify internal webpack config. If returned value is an Object, it
          // will be merged into the final config using webpack-merge;
          // If the returned value is a function, it will receive the config as the 1st argument and an isServer flag as the 2nd argument.
          return {
            plugins: [
              new webpack.DefinePlugin({
                // IMPORTANT: To fix debug library‘s bug
                // {}.DEBUG = namespaces; // SyntaxError: Unexpected token '.'
                'process.env.DEBUG': 'process.env.DEBUG',
              })
            ]
          }
        },
      }
    }
  ],
```

**Comment by nicobistolfi** [comment]
@Sakura-pgh you made my day ⭐

**Comment by Zenahr** [comment]
> I solved the problem by changing this in `docusaurus.config.js`
> 
> ```js
> plugins: [
>     ...
>     async function customPlugin(context, opts) {
>       return {
>         name: 'custom-plugin',
>         configureWebpack(config, isServer, utils, content) {
>           // Modify internal webpack config. If returned value is an Object, it
>           // will be merged into the final config using webpack-merge;
>           // If the returned value is a function, it will receive the config as the 1st argument and an isServer flag as the 2nd argument.
>           return {
>             plugins: [
>               new webpack.DefinePlugin({
>                 // IMPORTANT: To fix debug library‘s bug
>                 // {}.DEBUG = namespaces; // SyntaxError: Unexpected token '.'
>                 'process.env.DEBUG': 'process.env.DEBUG',
>               })
>             ]
>           }
>         },
>       }
>     }
>   ],
> ```

@Sakura-pgh Thank you SO MUCH. You've helped me tremendously in 2024. I was already debugging this issue for 2 days before stumbling on your comment.
