### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by victor-teles** [rohit-gohri/redocusaurus#56]
Hi @rohit-gohri,

first thanks for the great work.

i'm using redocusaurus in my project but i get error when build it:

Docusaurus Node/SSR could not render static page with path=/swagger/ because of error: Cannot read property 'style' of undefined

TypeError: Cannot read property 'style' of undefined
error building locale=en
Error: Failed to compile with errors.
    at /Users/<>/Documents/Projects/<>/docs/node_modules/@docusaurus/core/lib/webpack/utils.js:198:24
    at /Users/<>/Documents/Projects/<>/docs/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/M</Documents/Projects/<>/docs/node_modules/webpack/lib/MultiCompiler.js:492:6)
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rohit-gohri** [comment]
Could you confirm which version of docusaurus and which version of redocusaurus are you using?

**Comment by victor-teles** [comment]
"dependencies": {
    "@docusaurus/core": "2.0.0-beta.0",
    "@docusaurus/preset-classic": "2.0.0-beta.0",
    "redocusaurus": "^0.4.1",
    "clsx": "^1.1.1",
    "file-loader": "^6.2.0",
    "lightense-images": "^1.0.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "remark-mermaid-dataurl": "^1.0.1",
    "url-loader": "^4.1.1"
    "@mdx-js/react": "^1.6.21"
}

**Comment by rohit-gohri** [comment]
Could you try version `0.4.4`? I fixed other build issues in it, haven't been able to recreate this particular error though
